/*
 * Copyright 2012 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-beamnet
 *
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

/*
 * This class gathers together all the test cases for the gr-filter
 * directory into a single test suite.  As you create new test cases,
 * add them here.
 */

#include "qa_beamnet.h"

#include "qa_correlation_detector.h"


#include "qa_energy_detector.h"
#include "qa_symbol_sync.h"
#include "qa_packet_extraction.h"
#include "qa_packet_trigger.h"
#include "qa_source_pkt.h"
#include "qa_tx_slave_mux.h"
#include "qa_packet_demux.h"

CppUnit::TestSuite *
qa_beamnet::suite()
{
  CppUnit::TestSuite *s = new CppUnit::TestSuite("beamnet");

  s->addTest(gr::beamnet::qa_correlation_detector::suite());

  s->addTest(gr::beamnet::qa_energy_detector::suite());
  s->addTest(gr::beamnet::qa_symbol_sync::suite());
  s->addTest(gr::beamnet::qa_packet_extraction::suite());
  s->addTest(gr::beamnet::qa_packet_trigger::suite());
  s->addTest(gr::beamnet::qa_source_pkt::suite());
  s->addTest(gr::beamnet::qa_tx_slave_mux::suite());
  s->addTest(gr::beamnet::qa_packet_demux::suite());

  return s;
}
